DROP DATABASE IF EXISTS prg;
CREATE DATABASE prg;

USE prg;

CREATE TABLE exam (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	credits INT NOT NULL,
	mark INT NOT NULL,
	date DATE NOT NULL
);
